url: https://ds-changes.github.io
baseurl: ""

# Site settings
title: Data Science for Carbon Harvesting ANd the aGriculturE tranSition (DS-CHANGES)
email: dschanges@gmail.com
description: "Exploring the potential of carbon farming to transform agriculture and climate mitigation, supported by Fondazione Cariplo."

# Team names, titles and social links
people:
- name: Università degli Studi di Brescia
  pic: 1
  position: Project Partner
  social:
    - title: globe
      url: https://www.unibs.it/

- name: Scuola Superiore Sant’Anna
  pic: 2
  position: Project Partner
  social:
    - title: globe
      url: https://www.santannapisa.it/

- name: Fondazione Eni Enrico Mattei
  pic: 3
  position: Project Partner
  social:
    - title: globe
      url: https://www.feem.it/

# Social networks (modifica o aggiungi se vuoi)
social:
  - title: github
    url: https://github.com/ds-changes
  - title: email
    url: mailto:dschanges@gmail.com

# Postal address (se vuoi lo possiamo aggiornare)
address:
  - line: Milano, Italia

# Build settings
markdown: kramdown
permalink: pretty

# Optional: theme colors (da adattare al logo finale)
theme_color_primary: "#2C3E50"   # blu/grigio sobrio
theme_color_secondary: "#18BC9C" # verde acqua discreto
